### ISSUE TITLE
Transplant (SPL-HES) (OPCS4)

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#1075]
https://www.opencodelists.org/codelist/nhsd/transplant-spl-hes-opcs4/5b4c92d0/#full-list

`z94` looks like an ICD10 code - for the moment we will exclude this one alone while we check the rest of the list with NHS Digital

**Comment by rose-higgins** [comment]
The codelist [published](https://digital.nhs.uk/coronavirus/treatments/methodology/coding-classifications-used) for transplant codes in HES (using OPCS4) contain some ICD-10 codes, labelled as OPCS4 codes. This error in the codelist was spotted due to a much higher than expected prevalence of people being returned in the solid organ transplant high risk cohort. 

The code Z94 in OPCS4 is a subchapter describing laterality of procedures and is not in any way specific to transplant procedures. However, the same code in ICD-10 does in fact refer to 'Transplanted tissue and organ status' as a diagnosis code. 

A brief and non-comprehensive look through other codes in that codelist has revealed more codes which are mislabelled as OPCS4 and should be labelled as ICD-10. 

As an immediate fix: the transplant HES OPCS4 codelist has been updated, removing Z94, as this was the code contributing to the majority of erroneous inclusions in the analysis. The updated transplant HES (OPCS4) codelist can be found [here](https://www.opencodelists.org/codelist/nhsd/transplant-spl-hes-opcs4/1b47de52/). 

Next steps: to look into an automated way of validating code types using both codes and descriptions in opencodelists.

**Comment by rebkwok** [comment]
Closing as codes are now validated on upload (for snomedct, icd-10, dm+d, ctv3, bnf).  In this particular instance, that wouldn't help, because we don't fully support OPCS-4, we just allow codelists to be uploaded labelled as OPCS-4.  OpenCodelists contains no OPCS-4 data tha can be used for validation.
