### ISSUE TITLE
Convert some Y-codes to SNOMED codes

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#1291]
TPP use Y-codes (codes beginning with "Y") for concepts that do not (yet) have a CTV3 code.

There is a table in the TPP database called `YCodeToSnomedMapping` that contains mappings between Y-codes and SNOMED codes.

@andrewscolm has requested the equivalent SNOMED codes for all Y-codes in [this codelist](https://www.opencodelists.org/codelist/opensafely/covid-identification-in-primary-care-probable-covid-positive-test/508192f8/#full-list), as well as for these three:

* `Y9930` Race - British
* `Y9931` Race - Indian
* `Y9932` Race - Mediterranean

**Comment by rebkwok** [comment]
@andrewscolm These are the equivalent SNOMED codes for the Y codes in the codelist.  The 3 additional ethnicity ones do not have entries in the TPP `YCodeToSnomedMapping` table.

SNOMED | CTV3ID | CTV3PreferredTermDesc
-- | -- | --
1240581000000104 | Y20d1 | SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive
1240391000000107 | Y213a | Antigen of 2019-nCoV (novel coronavirus)
1300721000000109 | Y228d | Coronavirus disease 19 caused by severe acute respiratory syndrome coronavirus 2 confirmed by laboratory test (situation)
1240581000000104 | Y23f7 | SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detection result positive
1321301000000101 | Y240b | SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) qualitative existence in specimen
1324601000000106 | Y2a3b | SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) RNA (ribonucleic acid) detection result positive
1322781000000102 | Y269d | SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) antigen detection result positive
