### ISSUE TITLE
500 error for amputation codelist

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/opencodelists#1333]
@LisaHopcroft:

> Reporting that https://www.opencodelists.org/codelist/opensafely/amputation/2020-09-21/ is giving a Server Error (500)

I investigated and found this traceback:

```python
File "/app/codelists/views/version.py", line 32, in version
  for type, codes in coding_system.codes_by_type(
File "/app/coding_systems/ctv3/coding_system.py", line 133, in codes_by_type
  lookup[terms_by_type[code]].append(code)
KeyError: 'S84x2'
```

The [CSV download URL](https://www.opencodelists.org/codelist/opensafely/amputation/2020-09-21/download.csv) does work.

In it, you find:

```csv
S84x2,Unknown Redundant Concept
```

and lots more:

```csv
…
.P4B.,Unknown Redundant Concept
.P4B1,Unknown Redundant Concept
.P4B2,Unknown Redundant Concept
.P4B3,Unknown Redundant Concept
2G42.,Unknown Redundant Concept
2G43.,Unknown Redundant Concept
2G44.,Unknown Redundant Concept
2G45.,Unknown Redundant Concept
2G46.,Unknown Redundant Concept
2G47.,Unknown Redundant Concept
…
```

Some of these, like `2G45.`, `2G46.`, `2G47.` look like amputation-related codes, but for Read v2, and were moved in CTV3.

**Comment by rebkwok** [comment]
There are a few codelist versions that contain codes that aren't found in the coding system.  This can happen for old codelists that were created by uploading CSV data directly (not via the "create a codelist" form, which turns CSV data into code objects and raises errors if any codes are invalid). 

The following codelist versions are affected:

**Published:**
These are all old codelists that have invalid codes in them - either codes labelled "unknown" already in the uploaded CSV file, or that appear to actually be read V2 codes.
19 CTV3 (Read V3) /codelist/opensafely/stroke-deprecated/2020-04-21/
210 CTV3 (Read V3) /codelist/opensafely/amputation/2020-09-21/
213 CTV3 (Read V3) /codelist/opensafely/absence-of-appendix/2020-09-24/

Lots of these ones have invalid codes that are labelled "emis code", so probably known not to be real snomed ones.
228 SNOMED CT /codelist/ardens/blood-tests/2020-10-20/
232 SNOMED CT /codelist/ardens/interim-follow-up-review/2020-10-20/
233 SNOMED CT /codelist/ardens/invs-other/2020-10-20/
241 SNOMED CT /codelist/ardens/ca127/2020-11-06/
243 SNOMED CT /codelist/ardens/cholesterol-total-level/2020-11-06/
256 SNOMED CT /codelist/ardens/hdl-cholesterol/2020-11-06/
267 SNOMED CT /codelist/ardens/triglycerides/2020-11-06/

**Under review:**
These are newer codelists, but look like they were all created as "old-style" codelists, from CSV data directly (with errors in the CSV files).

Looks like these were caused by a CSV file with row number in, which are being interpreted as codes
4274 SNOMED CT /codelist/user/yayang/antibiotics_indication/1c0e91e1/
4275 SNOMED CT /codelist/user/yayang/antibiotics_indication/02ff1eac/

These all have odd-looking ethnicity codes - looks like maybe an excel->csv issue where long codes have been converted to e-notation (e.g. 92411000000108 to 9.2411E+13)
4775 SNOMED CT /codelist/user/caroline-morton/ethnicity-with-categories/10d21ac6/
5100 SNOMED CT /codelist/user/candrews/ethnicity_tpp/4034d83d/
5101 SNOMED CT /codelist/user/candrews/ethnicity_tpp_all/27256508/
5102 SNOMED CT /codelist/user/candrews/ethnicity-in-tpp/0e15f1d3/ (contains odd ethnicity codes)

These look like DMD codelist uploaded as Snomed/ICD-10
5248 SNOMED CT /codelist/user/alexorlek/aminoglycosides-antibacterial/43463d7c/
3604 ICD-10 /codelist/user/rriefu/icd/327e171a/
