### ISSUE TITLE
Investigate options for versioning coding systems

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#1379]
We know that we want to record the version of a coding system that was used to create a codelist.  A simple option would be to store only the latest release of a coding system, alongside its version identifier, and then to record the coding system version
identifier against each version of a codelist.

This is much better than the status quo, but while we're thinking about this, we should also consider whether we can store each release of a coding system.

This would bring several benefits:

 * it would allow us to understand the context in which a codelist was created
 * if two backends use different versions of SNOMED-CT, then we might want to maintain different versions of a codelist, so that if we discover that the codelist is missing a code, we can update both versions
 * it would allow us to support national flavours of SNOMED-CT

The output of this task should be a report outlining different options that have been considered, with the benefits, costs, and risks of each.

**Comment by rebkwok** [comment]
Thoughts so far [here](https://docs.google.com/document/d/1rstaBR4u6MpLfH4urfDA27mZyVowMuvrkUE7kOZFVuM/edit#)

**Comment by rebkwok** [comment]
@inglesp I've written down my thoughts about how we could implement coding system versioning with database routing and one database per version [here](https://gist.github.com/rebkwok/65bf170765910ed5846ef3c4311a6023)
Does this sound feasible?

**Comment by rebkwok** [comment]
PR #1397  implements the first steps of the multi-db proposal:

1) The new `coding_systems.versioning` app with one model, `CodingSystemVersion`, to hold information about a single import of a version of one coding system.

2) A function `update_coding_system_database_connections`, which adds the relevant database config from the `CodingSystemVersion` instances

3) A management command that extracts the current coding system tables from the main DB, creates an initial `CodingSystemVersion` instance for each coding system (with an "unknown" version, since this will be assigned initially to all the current CodelistVersions that pre-date the coding system versioning), and loads the tables into separate databases.

Next steps:
- generate the coding system version databases for real
- update the CodelistVersion model so they have a reference to their coding system version
- assign the relevant "unknown" coding system version instance
- update the coding system interface methods (`code_to_status` etc) to take an additional version hash parameter, and call any ORM methods with `.using(<version_db>)`
- update all the coding system `import_data` scripts to generate a new `CodingSystemVersion` and load to the relevant new database

**Comment by rebkwok** [comment]
PR #1401 implements the following:
- updates the CodelistVersion model so they have a reference to their coding system version
- (assuming coding system version dbs have already been run) assigns the "unknown" initial coding system version to existing CodelistVersions
- implements the versioning in the coding system interface methods
- Defaults all existing code that creates a version to use the most recent version (at this point, the "unknown" one)

Next steps (probably separate PRs and/or tasks): 
1) Update `import_data` scripts so new coding system imports will load to a new database - #1409
2) Import latest version of all coding systems so we have a defined "most recent" version 
3) Implement coding system versions in the `mappings` apps
4) Determine which codelists can be assigned to the latest coding system version (only those with searches, by rerunning searches and verifying they're identical?)
5) Allow users to select a coding system version when they create a new codelist / create a new draft from an existing codelist
6) Update `codelists.api.codelists_get` view to include the coding system version and valid_from date (only used by OSI, so need to confirm it's not going to affect anything there)

**Comment by rebkwok** [comment]
Questions about mapping:
PR #1415 updated the mapping apps (that convert ctv3 to snomedct and bnf to dmd).  However, for now it's just assuming that the Mapping itself is unaware of coding system versions, and it will just look up mapped codes based on the coding system it's provided (atm, always the most recent one).  This keeps conversions working as they do right now.

Q: Are mapping source data specific to certain coding system versions? e.g. there's a new release of DM+D to BNF mappings - do we know for sure which version of both DM+D and BNF it relates to?  Mappings are provided as excel files [here](https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping), appear to be released monthly, but I can't see any reference to a version of either system.

Q: I've updated the snomed to ctv3 conversions - but are they actually needed any more?  There's a view (which isn't exposed) for converting snomed to ctv3 (but not the other way round), which doesn't actually use the majority of the conversion code.

**Comment by rebkwok** [comment]
Closing in favour of tracking progress on #1446
