### ISSUE TITLE
Clarify system for dm+d codelists

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/opencodelists#1543]
The coding system for a [dm+d codelist](https://www.opencodelists.org/codelist/opensafely/dmards/2020-06-23/) is shown as `Dictionary of Medicines and Devices` on OpenCodelists. If I want to [use this codelist](https://github.com/opensafely/medication-reviews/blob/c576680ff3a63c773c0c2a84233da9a828038ee7/analysis/codelists.py#L63-L66) in OpenSAFELY, the codelist type has to be specified as `snomed`.  Could we make it clearer that [dm+d is an extension of SNOMED-CT](https://www.bennett.ox.ac.uk/blog/2022/11/difference-between-bnf-dm-d-and-snomed-ct-codes/#nhs-dictionary-of-medicines-and-devices-dmd) by displaying the system on OpenCodelists as `SNOMED-CT (Dictionary of Medicines and Devices)`?

**Comment by rebkwok** [comment]
I think it's more complicated than that.  I don't think we sholud label dm+d as SNOMED-CT, because that's not what it's called  on the source page.
https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/dictionary-medicines-and-devices-dmd

But also, despite the fact that cohort-extractor requires you to specify the system as "snomed", it's actually looking up codes as DMD_ID in the real data. 
https://github.com/opensafely-core/cohort-extractor/blob/main/cohortextractor/tpp_backend.py#L1095

And, this confusion should all go away in databuilder anyway.

**Comment by rebkwok** [comment]
Closing as this becomes irrelevant with ehrQL
