### ISSUE TITLE
'Create new version' creates dumb copy

### ISSUE THREAD

**Issue by ciaranmci** [opensafely-core/opencodelists#1563]
When I select 'Create new version' of one of my codelists, a new draft is created but nothing can be done with it. Please, see examples below of attempted new versions that are dumb copies. __Any ideas why this might be happening?__

<img width="460" alt="image" src="https://github.com/opensafely-core/opencodelists/assets/44294573/caffce3a-69a2-4155-90f0-197f23cde2e2">

<img width="467" alt="image" src="https://github.com/opensafely-core/opencodelists/assets/44294573/52cdcca2-7876-4624-80cd-53afd420d32e">

<img width="465" alt="image" src="https://github.com/opensafely-core/opencodelists/assets/44294573/bd21f07d-c8d0-4674-8f8a-85e6459b24b6">

**Comment by rebkwok** [comment]
@ciaranmci This bug is fixed now, and I've updated the first two drafts mentioned: 
https://www.opencodelists.org/builder/065ce2a1/
https://www.opencodelists.org/builder/1f6c55d6/

Both of these contain some new codes that were not on the original codelist version (due to changes to the coding system since that version was created:
1186821000
1186823002
191574005
1186826005
1204417003
1186832000

These codes have all been implicitly included due to the inclusion of a parent code - please check them and make sure that's correct.

(The 3rd version has also been updated, but it's currently timing out - possibly it's just too big, I'll have a look into it)

**Comment by rebkwok** [comment]
@ciaranmci Thanks, those two are now deleted.
