### ISSUE TITLE
Codes statuses reset in builder 

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1811]
See [slack thread](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1706020368387649)

As described by user: she does a search (e.g. "influena") which brings back ~1300 codes. She resolves them all, clicks on a filter (e.g. "included") and it shows >1000 as unresolved. This has happened multiple times, although she is eventually able to get all the codes to resolve (but obviously having to repeat 1000+button clicks is awful). She's been able to manage it by regularly saving the draft while she's building it.

I can't reproduce this. Each click on a +/- in the builder posts to `builder/<hash>/update` with  the code and its new applied status.  It uses [this function](https://github.com/opensafely-core/opencodelists/blob/main/builder/actions.py#L91) to build a new codeset with the new code status, and updates the status of ALL drafts `CodeObj`s, based on the newly created codeset.  My only hypothesis is that there's a race condition where somehow an early /update request which has a built a codeset with lots of unresolved statuses is delayed, then processed later and so wipes out the previous updates. But I don't know why this would happen (and seems to be specific to Em - I'm fairly sure other users would have complained if it had been happening often).

Also, I'm certain that saving the draft during the build is not doing anything other than slowing down the update requests - "save draft" does nothing but reload the draft page, it doesn't actually do any saving of the model or its code objects.

**Comment by rebkwok** [comment]
Another hypothesis:
Clicking one of the filters (included/excluded/in conflict/unresolved) also rebuilds the codelist's Codeset using its CodeObjs, and returns the filtered codes with the hierarchy built from them.  If the /update requests haven't completed, clicking on a filter could be retrieving and displaying a new Codeset with statuses that haven't yet updated

**Comment by iaindillingham** [comment]
The issue was reported to tech support on 23 Jan. It relates to `builder/<hash>/update/`. [Sentry reports](https://ebm-datalab.sentry.io/issues/4058862808/?project=5248013) four errors for two users for this URL: `OperationalError` database is locked. (There were also three errors of the same type for three users for `builder/<hash>/search/`.)

The associated queries seem to have a lot of codes in their `IN`s

https://github.com/opensafely-core/opencodelists/blob/87dc2a75776ba449e98571de8eb6aaca7487fdb0/builder/actions.py#L99

Possibly the issue is less about the builder, and more about concurrency?

There's a 30s timeout on the SQLite DB.

https://github.com/opensafely-core/opencodelists/blob/87dc2a75776ba449e98571de8eb6aaca7487fdb0/opencodelists/settings.py#L137-L152

We seem to hit concurrency issues at both of these URLs often: 50 in the last 30 days. (Although they seem to be confined to two users: Em and Vicky.

How would you feel about increasing the timeout to, say, 45s @rebkwok?

**Comment by rebkwok** [comment]
The `OperationalError database is locked.` issue is one that OpenCodelists sees quite often and we've never quite got to the bottom of.

> How would you feel about increasing the timeout to, say, 45s @rebkwok?
Worth a try :)

**Comment by evansd** [comment]
I'm pretty sure we're already running in WAL mode, but might be worth looking at:
```
PRAGMA synchronous = normal;
```
as well (if we're not already).

Some useful advice here:
https://phiresky.github.io/blog/2020/sqlite-performance-tuning/

**Comment by iaindillingham** [comment]
Thanks, @rebkwok and @evansd.

**Comment by iaindillingham** [comment]
> I'm pretty sure we're already running in WAL mode

I thought it would be easy to find this out, but I was wrong. I was expecting to find it in `opencodelists/settings.py`, possibly as part of `DATABASES`. Alternatively, where the `connection_created` signal was called. Could you point me in the right direction, @evansd?

**Comment by evansd** [comment]
Journal mode is sightly odd in that you set it by issuing a `PRAGMA` command and then it gets persisted to the file and stays set for all subsequent connections.

So I suspect someone did it by hand at one stage. It would definitely be better to configure it somewhere in the code though.

The way I confirmed that we are using WAL mode was like this:
```
sssh dokku3.ebmdatalab.net
dokku enter opencodelists web sqlite3 -readonly /storage/db.sqlite3 'PRAGMA journal_mode'
```

Which prints: `wal`.

**Comment by iaindillingham** [comment]
Thanks, @evansd.

**Comment by rebkwok** [comment]
We are runnning in WAL mode, it was turned on several months ago in an attempt to fix the database locked issue
