### ISSUE TITLE
Try Cloudflare's bad bot protections

### ISSUE THREAD

**Issue by mikerkelly** [opensafely-core/opencodelists#2217]
# Why are we doing this?

The [Honeycomb dashboard](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/board/4ngq7kuV7z/OpenCodelists-Django-app) created in #2133 highlights significant bot activity on the site. While we support responsible bot use, it's likely some of this activity comes from malicious bots. Attempting to block these bots from reaching Django could improve our compute efficiency somewhat and reduce the extent to which Honeycomb stats are dominated by their traffic. It might also reduce the risk that they discover security holes.

Examples of malicious bot activity include attempts to access common potentially exploitable PHP scripts (e.g., `/admin.php`) or AI scrapers targeting `/.well-known/traffic-advice`.

# How will we know when it's done?

Options below and anything else discovered will have been explored and implemented where feasible. Probably this should take no more than a few hours to explore.

We should monitor traffic via the dashboard before and after making changes.

# What are we doing?

Cloudflare offers features designed to mitigate malicious bot traffic. These features are quick to enable or disable via a configuration page, making them easy to test. However, we should consider potential unintended side effects, such as blocking legitimate bots or users, and consider whether we can monitor for these issues post-deployment. However, Cloudflare probably have put a lot more thought into this than we can, so we can rely on them to some extent. We'd also receive user reports for major problems.

Note that this will be more useful if we do #2145 and non-Cloudflare requests don't get through.

You may need to request access to Cloudflare. This isn't currently documented (see [team-manual issue 950](https://github.com/ebmdatalab/team-manual/issues/950)) so ask in #tech.

Some of the options in Cloudflare:
* Block bad bots and AI bots.
* Potential blocks we can add in to the firewall, with a couple of options we can turn on if we don't want to just block.
* We can also block based on Country, if lots of bots are coming from an unfriendly country.

![Image](https://github.com/user-attachments/assets/5be88ede-089c-4e2a-81a8-6165d3bbb53e)

![Image](https://github.com/user-attachments/assets/9db159a1-39d1-40ca-8dd3-28e430197811)

---
[Defining delivery tasks guidance](https://docs.google.com/document/d/1F7yBNYnMoCW3liWVvjPXFHnrnCU4qeAOhlKBVD1-8lg/edit?tab=t.0#heading=h.qkl5vvsdkx98)

**Comment by lucyb** [comment]
Unfortunately, we have discovered that GitHub Actions count as a "bad bot" by Cloudflare ([thread](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1734620544458609)). I've turned this off temporarily, pending further investigations.

**Comment by tomodwyer** [comment]
As Lucy's message stated, the Bot Fight Mode enabled in Cloudflare caused issues with `python-request` from GitHub Actions.

Instead of switching that back on, I have set up the Firewall in Cloudflare to count two types of users, and take no action.

## PHP Users

The first group is users who access PHP files. This is a simple wildcard rule for any user who sends a request to `/*.php` on OpenCodelists. [The firewall activity can be viewed in the Dashboard](https://dash.cloudflare.com/29eda675cdba63fecfdeb3947b930874/opencodelists.org/security/events?rule-id=d308a46a2935496f97145f6aaf9dc2ad).

## Bots

The second group is all Known Bots, as Cloudflare defines them. This will include good and bad bots, and lists all the hits to the website from them. [The firewall activity can be viewed in the Dashboard](https://dash.cloudflare.com/29eda675cdba63fecfdeb3947b930874/opencodelists.org/security/events?rule-id=894a61cc07914578962eb74dae67336a).

## Next steps

I believe this issue should be closed in favour of reviewing the stats in the new year. once the stats have been reviewed, we should consider what users and bots we want to block, and apply very specific rules to block them. One example would be allowing all bots to the API, but blocking bad bots from accessing all other URLs.

**Comment by Jongmassey** [comment]
>can be viewed in the Dashboard


>404 | Either this page does not exist, or you do not have permission to access it

**Comment by tomodwyer** [comment]
Reminder added to discuss WAF rules in a months time.
