### ISSUE TITLE
Term Search Delete

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#358]
It would be helpful if term searches could be deleted when building a codelists if you decide they aren't necessary.

For example when building an [antiplatelet](https://codelists.opensafely.org/builder/brian-mackenna/antiplatelet-medication/search/0209/) codelist  I entered `0209` and got ostomy bag. I know for definite then that my first term `antiplatelet` identified everything and I do not need anything from `0209` term. It would be preferable to delete 9~this is simple example) but only way I can see to get rid is to manually exclude everything irrelevant from `0209`

![image](https://user-images.githubusercontent.com/40460354/99962661-7cf27a00-2d88-11eb-878f-0e8b5cead861.png)

**Comment by Auselan** [comment]
Is it better to delete the keyword, or be able to mark it as 'redundant'?

Mission goals approached in doing so:
- Transparency improved
- Collaboration improved

Example: when Merlin creates a code list and asks me to validate it, he might have searched for 0209 himself, before realising that it was redundant.  To validate his code list, I might search for 0209 myself (or Antiplatelet Drugs for example) in order to validate that he was correct.  If I could see that he had already searched for 0209, found it and disregarded it from his list, I would like the builder to save me the time in recreating his steps, or even to be able to see what he did.

I want to be able to see his keyword searches, and review what they found - that is quicker for me than thinking of the all for myself, and typing the keywords in.  I suggest 2 functions

- delete search term (i.e. I made a typo in my search, or messed up what I was searching for, and this keyword search is not going to be helpful to anyone ever)
- mark search term as redundant (possibly with additional markup i.e. Option 1: all codes are included in the list already Option 2: there are no useful terms found using this keyword Option 3: other reason - specify)

**Comment by inglesp** [comment]
> Is it better to delete the keyword, or be able to mark it as 'redundant'?

It's definitely important to be able to delete a search term -- the other day a user was building a codelist for TIA, searched for "tia", and got back thousands of results including dementia, dietitian, partial excision of bone, Croatian as a second language, etc!

**Comment by Auselan** [comment]
A good example to discuss.  To me you illustrate the exact opposite:

1. this illustrates a development requirement for the engine - handling acronyms.  Short string queries are likely to return huge numbers of results UNLESS an input mask or equivalent is put in place to guide the search results in that instance.  The query may be better of warning the user before proceeding, OR offering the option of ONLY returning results where the letters typed in had a nonbreaking space before and after it for example |High risk of TIA (transient ischaemic attack)| would have been helpful.  The search engine needs to evolve to match the way the person building the list thinks
2. if I validate a code list done by someone else, one of the terms I'm going to put in is TIA, so if I can see that it was already searched for (and abandoned/dropped/another descriptor) AND WHY, it is going to save me time in the validation of the code list.  If the person building the list simply deletes it, I'm going to waste my time recreating exactly what they did

**Comment by gpessoaamorim** [comment]
Hi everyone, thanks @brianmackenna for pointing me towards this - definitely something I also realised would be helpful when using the platform

My other suggestion (in addition or as an alternative) would be to have a button to mark all results of a search as not for inclusion, and then only having to actively click the ones you want to include. This would facilitate building lists based on general terms that you are not sure how to restrict - and becomes an issue particularly if appliances and the like get pulled in the string search as a lot of the time they are not group. I think this would also address the concern mentioned by @Auselan
